apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orbguard

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: orbguard
  app.kubernetes.io/part-of: orbguard-lab
  app.kubernetes.io/managed-by: kustomize

images:
  - name: orbguard/orbguard-lab
    newTag: latest
