apiVersion: v1
kind: ServiceAccount
metadata:
  name: orbguard
  namespace: orbguard
  labels:
    app: orbguard-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orbguard
  namespace: orbguard
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orbguard
  namespace: orbguard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orbguard
subjects:
  - kind: ServiceAccount
    name: orbguard
    namespace: orbguard
